# King Count Houses - Insight  Project

# Basic setups

## IMPORTS

In [1]:
import math
import plotly.express as px
import pandas as pd
from IPython.core.display     import HTML
import seaborn       as sns
import datetime
import ipywidgets as widgets
from   ipywidgets import fixed

## Helper functions

In [2]:
def jupyter_settings():
    %matplotlib inline
    %pylab inline
    plt.style.use( 'bmh' )
    plt.rcParams['figure.figsize'] = [25, 12]
    plt.rcParams['font.size'] = 24
    display( HTML( '<style>.container { width:100% !important; }</style>') )
    pd.options.display.max_columns = None
    pd.options.display.max_rows = None
    pd.set_option( 'display.expand_frame_repr', False )
    sns.set()
jupyter_settings()

Populating the interactive namespace from numpy and matplotlib


# Data Load

In [10]:
df_raw = pd.read_csv(r'../data/raw/kc_house_data.csv') 

## Data Overview

In [11]:
df_raw.sample(5)

id             date     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15
943    8820901670  20140811T000000  971000.0         5       3.50         4390     10140     2.0           0     0          3      9        3350           1040      2005             0    98125  47.7174 -122.282           2010        8400
17729  1705400361  20141208T000000  600000.0         2       1.00         2120      6897     1.0           0     0          4      7        1060           1060      1923             0    98118  47.5566 -122.278           1900        4462
20170  6626300095  20140519T000000  749950.0         4       2.50         3430     64441     2.0           0     0          3      8        3430              0      2013             0    98077  47.7694 -122.064           3580       64441
3558   4040200490  20140820T000000  461000.0         3       1.75         1420      5170     1.0           0     0          4      7        1420              0      1963             0    98007  47.6151 -122.145           2250        7700
16884  1088800470  20141028T000000  547500.0         3       2.50         2550     10355     2.0           0     0          3      9        2550              0      1990             0    98011  47.7390 -122.203           2550       10084

In [12]:
print ('The original dataset have {} transation registers with {} attributes.'.format(df_raw.shape[0], df_raw.shape[1]))

The original dataset have 21613 transation registers with 21 attributes.


# Data Analisys/Explorer

In [13]:
df3 = df_raw.copy()

In [24]:
df3.sample(5)

id             date     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15
15543  8732130680  20141027T000000  210000.0         3       2.25         2140      9775     1.0           0     0          4      7        1470            670      1978             0    98023  47.3060 -122.379           2050        8625
5486   2323069073  20140622T000000  439500.0         3       2.50         2050     40003     1.0           0     0          4      8        1570            480      1977             0    98027  47.4700 -122.000           2700       46769
14606   968000120  20141112T000000  395000.0         3       2.00         1470     10125     1.0           0     0          4      7        1470              0      1962             0    98011  47.7751 -122.222           1440       10125
3515   6648760100  20140711T000000  299950.0         3       2.50         1600      9830     2.0           0     0          4      8        1600              0      1993             0    98001  47.3390 -122.266           1890        8910
6490   1843130980  20140506T000000  284000.0         4       2.50         2000      5390     2.0           0     0          3      7        2000              0      2003             0    98042  47.3732 -122.129           2330        5390

1° Task: Whats the meaning and relevance of these attributes: 'grade','sqft_living15', 'sqft_lot15' and 'view'?
Identify, cleaning or drop

## Data Cleaning


### Data Types

In [25]:
df3.dtypes

id                 int64
date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

Tasks:
2°)Change 'waterfront' from 0 or 1 to yes or no
3°)Change 'date' to date format

### Check NA

In [26]:
df3.isna().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

## Check Duplicated

In [27]:
df3['id'].duplicated().sum()

177

Task:
4) Identify the duplicated ones and drop if it is necessary

# Data Transform/Preparing

In [28]:
df4 = df3.copy()

In [20]:
# attribute grade
df4['grade'].unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13,  1], dtype=int64)

It's an index from 1 to 13, where 1-3 falls short of building construction and design, 7 has an average level of construction and design, and 11-13 have a high quality level of construction and design.
***Definition*** - Change the attribute 'grade' to low_quality_design, average_quality_design and high_quality_design

In [21]:
df4['grade'] = df4['grade'].apply (lambda x:   'high_quality_design' if x >=11 else 
                                                'avg_quality_design' if (x>3) & (x<=10) else
                                                'low_quality_design'                         )

In [29]:
# attribute 'sqft_living15', 
df4['sqft_living15'].unique()

array([1340, 1690, 2720, 1360, 1800, 4760, 2238, 1650, 1780, 2390, 2210,
       1330, 1370, 2140, 1890, 1610, 1060, 1280, 1400, 4110, 2240, 1220,
       2200, 1030, 1760, 1860, 1520, 2630, 2580, 1390, 1460, 1570, 2020,
       1590, 2160, 1730, 1290, 2620, 2470, 2410, 3625, 1580, 3050, 1228,
       2680,  970, 1190, 1990, 1410, 1480, 2730, 1950, 2250, 2690, 2960,
       2270, 2570, 2500, 1440, 2750, 2221, 1010, 3390, 3530, 1640, 1510,
       2420, 1940, 3240, 1680,  890, 1130, 3350, 2350, 1870, 1720, 1850,
       1900, 1980, 2520, 1350, 1750, 1160, 2550, 2370, 1240, 1270, 2990,
       1380, 1540, 2090, 2640, 1830, 1620, 1880, 2340, 1710, 2700, 3060,
       2660, 1700, 1970, 1420, 2060, 2480, 1550, 1170, 2820, 1560, 2230,
       2840, 1450, 1500, 3160, 1200, 3400, 2110, 2920, 1770, 1070, 1930,
       3740, 2260, 1670, 2290, 1050, 2540, 2190, 2030, 1230, 2330, 1300,
       1430, 2770, 1250, 1630, 2590, 2130, 1100, 3836, 1320, 2120, 3070,
       1910, 2080, 1960, 2280, 1150, 3430, 2070, 26

In [30]:
# attibute 'sqft_lot15'
df4['sqft_lot15'].unique()

array([5650, 7639, 8062, ..., 5731, 1509, 2007], dtype=int64)

sqft_living15 - The square footage of interior housing living space for the nearest 15 neighbors
sqft_lot15 - The square footage of the land lots of the nearest 15 neighbors

Task:
Drop these features

In [31]:
df4 = df4.drop(columns = ['sqft_living15', 'sqft_lot15'], axis = 1)
df4.head()

id             date     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat     long
0  7129300520  20141013T000000  221900.0         3       1.00         1180      5650     1.0           0     0          3      7        1180              0      1955             0    98178  47.5112 -122.257
1  6414100192  20141209T000000  538000.0         3       2.25         2570      7242     2.0           0     0          3      7        2170            400      1951          1991    98125  47.7210 -122.319
2  5631500400  20150225T000000  180000.0         2       1.00          770     10000     1.0           0     0          3      6         770              0      1933             0    98028  47.7379 -122.233
3  2487200875  20141209T000000  604000.0         4       3.00         1960      5000     1.0           0     0          5      7        1050            910      1965             0    98136  47.5208 -122.393
4  1954400510  20150218T000000  510000.0         3       2.00         1680      8080     1.0           0     0          3      8        1680              0      1987             0    98074  47.6168 -122.045

In [32]:
# attribute 'view'
df4['view'].unique()

array([0, 3, 4, 2, 1], dtype=int64)

view - An index from 0 to 4 of how good the view of the property was
***Decision*** keep this for now

2)Change 'waterfront' from 0 or 1 to yes or no

In [ ]:
df4['waterfront'] = df4['waterfront'].apply(lambda x: 'yes' if x==1 else 'no')

3)Change 'date' to date format

In [ ]:
#date
df4['date'] = pd.to_datetime(df4['date'])
#year built
df4['yr_built']

4) Identify the duplicated ones and drop if it is necessary

In [36]:
df_dup  = df4[df4['id'].duplicated()].reset_index()
df_dup.head()

index          id             date      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat     long
0     94  6021501535  20141223T000000   700000.0         3       1.50         1580      5000     1.0           0     0          3      8        1290            290      1939             0    98117  47.6870 -122.386
1    314  4139480200  20141209T000000  1400000.0         4       3.25         4290     12103     1.0           0     3          3     11        2690           1600      1997             0    98006  47.5503 -122.102
2    325  7520000520  20150311T000000   240500.0         2       1.00         1240     12092     1.0           0     0          3      6         960            280      1922          1984    98146  47.4957 -122.352
3    346  3969300030  20141229T000000   239900.0         4       1.00         1000      7134     1.0           0     0          3      6        1000              0      1943             0    98178  47.4897 -122.240
4    372  2231500030  20150324T000000   530000.0         4       2.25         2180     10754     1.0           0     0          5      7        1100           1080      1954             0    98133  47.7711 -122.341

6°)Task: All the duplicated one with the same date will be considered errors, the ones with different dates will be keep

# Data Exploration

## Descriptive Statistics

## Numerical Attributes

## Categorical Attributes

## Univariated Analisys

## Multivariated Analisys

# Feature Engeneering

In [ ]:
# Prmary Hipotesys
1) Houses with waterview are more expensive
2) Houses with garage are more expensive
3) There is a main feature that raise the prices?

In [ ]:
## Average price per zipcode

In [ ]:
## Price level (cheap, average expensive)

In [ ]:
## Should buy

# Conclusion

# Next steps